version: '3.3'

services:
  api-gateway:
    image: tourguide-api-gateway
    container_name: tourguide-api-gateway
    ports:
      - 8080:8080
    networks:
      - tourguide-net
    depends_on:
      - rewards
      - gps
      - users
    restart: always

  rewards:
    image: tourguide-rewards
    container_name: tourguide-rewards
    ports:
      - 9003:9003
    networks:
      - tourguide-net
    restart: always

  gps:
    image: tourguide-gps
    container_name: tourguide-gps
    ports:
      - 9002:9002
    networks:
      - tourguide-net
    restart: always

  users:
    image: tourguide-users
    container_name: tourguide-users
    ports:
      - 9001:9001
    networks:
      - tourguide-net
    restart: always

networks:
  tourguide-net:
      driver: bridge
